/* figures.js — the diagrams geometry questions need.
   Every figure is inline SVG built from the same numbers the question uses, so a
   drawing can never disagree with its own text. Colours come from the page's CSS
   variables and strokes from currentColor, so figures work in both themes without
   a second copy.

   A figure is a plain SVG string assigned to a question's `figure` field. It is
   generated by this file only — never from learner input — and tests/t-figures.js
   checks that nothing scriptable gets into one. */
(function (root) {
  'use strict';
  var MC = root.MC || require('./mathcore.js');

  var INK = 'currentColor';
  var ACC = 'var(--accent)';
  var MUT = 'var(--ink-3)';

  function esc(s) { return MC.esc(String(s)); }

  /* Wrap a body in a responsive, theme-aware svg. */
  function svg(w, h, body, label) {
    return '<svg class="fig" viewBox="0 0 ' + w + ' ' + h + '" role="img" aria-label="' +
      esc(label || 'geometry diagram') + '" preserveAspectRatio="xMidYMid meet">' + body + '</svg>';
  }
  function line(x1, y1, x2, y2, opt) {
    opt = opt || {};
    return '<line x1="' + r(x1) + '" y1="' + r(y1) + '" x2="' + r(x2) + '" y2="' + r(y2) +
      '" stroke="' + (opt.colour || INK) + '" stroke-width="' + (opt.w || 1.6) + '"' +
      (opt.dash ? ' stroke-dasharray="5 4"' : '') + ' stroke-linecap="round"/>';
  }
  function poly(pts, opt) {
    opt = opt || {};
    return '<polygon points="' + pts.map(function (p) { return r(p[0]) + ',' + r(p[1]); }).join(' ') +
      '" fill="' + (opt.fill || 'none') + '" stroke="' + (opt.colour || INK) +
      '" stroke-width="' + (opt.w || 1.6) + '" stroke-linejoin="round"/>';
  }
  function circle(cx, cy, rad, opt) {
    opt = opt || {};
    return '<circle cx="' + r(cx) + '" cy="' + r(cy) + '" r="' + r(rad) + '" fill="' +
      (opt.fill || 'none') + '" stroke="' + (opt.colour || INK) + '" stroke-width="' + (opt.w || 1.6) + '"/>';
  }
  function dot(cx, cy, opt) {
    opt = opt || {};
    return '<circle cx="' + r(cx) + '" cy="' + r(cy) + '" r="' + (opt.rad || 3) + '" fill="' +
      (opt.colour || INK) + '"/>';
  }
  function text(x, y, s, opt) {
    opt = opt || {};
    /* A halo in the card colour keeps a label legible where a line passes behind it. */
    var halo = opt.halo === false ? '' :
      ' stroke="var(--card)" stroke-width="3.5" stroke-linejoin="round" paint-order="stroke"';
    return '<text x="' + r(x) + '" y="' + r(y) + '" fill="' + (opt.colour || INK) +
      '" font-size="' + (opt.size || 13) + '" font-family="IBM Plex Mono, ui-monospace, monospace"' +
      ' text-anchor="' + (opt.anchor || 'middle') + '"' +
      (opt.weight ? ' font-weight="' + opt.weight + '"' : '') + halo + '>' + esc(s) + '</text>';
  }

  /* an arc marking an angle at a vertex, between two bearings in degrees */
  function arc(cx, cy, rad, from, to, opt) {
    opt = opt || {};
    var a1 = from * Math.PI / 180, a2 = to * Math.PI / 180;
    var x1 = cx + rad * Math.cos(a1), y1 = cy - rad * Math.sin(a1);
    var x2 = cx + rad * Math.cos(a2), y2 = cy - rad * Math.sin(a2);
    var large = Math.abs(to - from) > 180 ? 1 : 0;
    return '<path d="M ' + r(x1) + ' ' + r(y1) + ' A ' + r(rad) + ' ' + r(rad) + ' 0 ' + large +
      ' 0 ' + r(x2) + ' ' + r(y2) + '" fill="none" stroke="' + (opt.colour || ACC) +
      '" stroke-width="' + (opt.w || 1.5) + '"/>';
  }
  /* the little square that marks a right angle at vertex v, between two neighbours */
  function rightAngle(v, p, q, size) {
    size = size || 10;
    var u1 = unit(v, p), u2 = unit(v, q);
    var a = [v[0] + u1[0] * size, v[1] + u1[1] * size];
    var b = [v[0] + u1[0] * size + u2[0] * size, v[1] + u1[1] * size + u2[1] * size];
    var c = [v[0] + u2[0] * size, v[1] + u2[1] * size];
    return '<path d="M ' + r(a[0]) + ' ' + r(a[1]) + ' L ' + r(b[0]) + ' ' + r(b[1]) + ' L ' +
      r(c[0]) + ' ' + r(c[1]) + '" fill="none" stroke="' + INK + '" stroke-width="1.3"/>';
  }
  function unit(from, to) {
    var dx = to[0] - from[0], dy = to[1] - from[1], L = Math.hypot(dx, dy) || 1;
    return [dx / L, dy / L];
  }
  function r(n) { return Math.round(n * 100) / 100; }
  /* tick marks across a segment, to show equal sides */
  function ticks(p, q, n) {
    var mx = (p[0] + q[0]) / 2, my = (p[1] + q[1]) / 2;
    var u = unit(p, q), perp = [-u[1], u[0]];
    var out = '';
    for (var i = 0; i < n; i++) {
      var off = (i - (n - 1) / 2) * 5;
      var cx = mx + u[0] * off, cy = my + u[1] * off;
      out += line(cx - perp[0] * 5, cy - perp[1] * 5, cx + perp[0] * 5, cy + perp[1] * 5, { w: 1.3 });
    }
    return out;
  }

  /* ---------- the figures generators actually ask for ---------- */

  /* Two rays from a shared vertex with the angle marked and labelled. */
  function angleAt(deg, label) {
    var W = 260, H = 150, L = 100, a = deg * Math.PI / 180;
    /* centre the drawing, so an obtuse angle's second arm is not cut off the edge */
    var left = Math.min(0, L * Math.cos(a));
    var v = [(W - (L - left)) / 2 - left, 128];
    var p = [v[0] + L, v[1]];
    var q = [v[0] + L * Math.cos(a), v[1] - L * Math.sin(a)];
    var body = line(v[0], v[1], p[0], p[1]) + line(v[0], v[1], q[0], q[1]) +
      (Math.abs(deg - 90) < 0.5 ? rightAngle(v, p, q, 12) : arc(v[0], v[1], 34, 0, deg)) +
      dot(v[0], v[1]) +
      text(v[0] + 48 * Math.cos(a / 2) + 6, v[1] - 48 * Math.sin(a / 2) + 5, label === undefined ? deg + '\u00b0' : label,
        { colour: ACC, anchor: 'start', weight: 500 });
    return svg(W, H, body, 'an angle of ' + deg + ' degrees');
  }

  /* Two angles sharing a vertex: adjacent pair on a straight line, or vertical pair. */
  function anglePair(kind, known, label) {
    var W = 260, H = 160, body = '', lab = label === undefined ? '?' : label;
    var a = known * Math.PI / 180, v;
    if (kind === 'linear') {
      v = [130, 118];
      var len = 105, rl = Math.min(len, 92 / Math.sin(a));        /* the ray must stay on the canvas */
      body += line(v[0] - len, v[1], v[0] + len, v[1]);
      body += line(v[0], v[1], v[0] + rl * Math.cos(a), v[1] - rl * Math.sin(a));
      body += arc(v[0], v[1], 30, 0, known) + arc(v[0], v[1], 44, known, 180, { colour: MUT });
      body += text(v[0] + 40 * Math.cos(a / 2), v[1] - 40 * Math.sin(a / 2) - 4, known + '\u00b0', { colour: ACC });
      var mid = (known + 180) / 2 * Math.PI / 180;
      body += text(v[0] + 62 * Math.cos(mid), v[1] - 62 * Math.sin(mid) - 4, lab, { colour: MUT });
    } else if (kind === 'vertical') {
      v = [130, 80];
      var cl = Math.min(110, 62 / Math.sin(a));
      body += line(v[0] - 110, v[1], v[0] + 110, v[1]);
      body += line(v[0] - cl * Math.cos(a), v[1] + cl * Math.sin(a), v[0] + cl * Math.cos(a), v[1] - cl * Math.sin(a));
      body += arc(v[0], v[1], 28, 0, known) + arc(v[0], v[1], 28, 180, 180 + known, { colour: MUT });
      body += text(v[0] + 40 * Math.cos(a / 2), v[1] - 40 * Math.sin(a / 2) - 3, known + '\u00b0', { colour: ACC });
      body += text(v[0] - 40 * Math.cos(a / 2), v[1] + 40 * Math.sin(a / 2) + 11, lab, { colour: MUT });
    } else {                                                        /* complementary: inside a right angle */
      v = [55, 128];
      body += line(v[0], v[1], v[0] + 120, v[1]) + line(v[0], v[1], v[0], v[1] - 100);
      body += line(v[0], v[1], v[0] + 105 * Math.cos(a), v[1] - 105 * Math.sin(a), { dash: true });
      body += rightAngle(v, [v[0] + 120, v[1]], [v[0], v[1] - 100], 12);
      body += arc(v[0], v[1], 34, 0, known);
      body += text(v[0] + 48 * Math.cos(a / 2), v[1] - 48 * Math.sin(a / 2) + 4, known + '\u00b0',
        { colour: ACC, anchor: 'start' });
      var m2 = (known + 90) / 2 * Math.PI / 180;
      body += text(v[0] + 62 * Math.cos(m2), v[1] - 62 * Math.sin(m2), lab, { colour: MUT, anchor: 'start' });
    }
    body += dot(v[0], v[1]);
    return svg(W, H, body, 'a pair of angles');
  }

  /* Two parallel lines cut by a transversal, with one angle given. */
  function transversal(known, position) {
    var W = 280, H = 190;
    var y1 = 55, y2 = 140, slope = 0.55;
    var body = line(20, y1, 260, y1) + line(20, y2, 260, y2);
    /* transversal through both */
    var tx1 = 70, tx2 = 70 + (y2 - y1 + 70) * slope;
    body += line(tx1 - 40 * slope, y1 - 40, tx2 + 40 * slope, y2 + 40);
    var ix1 = [tx1, y1], ix2 = [tx1 + (y2 - y1) * slope, y2];
    body += dot(ix1[0], ix1[1]) + dot(ix2[0], ix2[1]);
    /* arrow marks showing the lines are parallel */
    body += text(245, y1 - 7, '›', { colour: MUT, size: 16 });
    body += text(245, y2 - 7, '›', { colour: MUT, size: 16 });
    body += text(ix1[0] + 16, y1 - 10, known + '°', { colour: ACC, anchor: 'start' });
    var lab = { corresponding: [ix2[0] + 16, y2 - 10], alternate: [ix2[0] - 14, y2 - 10],
                cointerior: [ix2[0] + 16, y2 - 10] }[position] || [ix2[0] + 16, y2 - 10];
    body += text(lab[0], lab[1], '?', { colour: MUT, anchor: position === 'alternate' ? 'end' : 'start' });
    return svg(W, H, body, 'two parallel lines cut by a transversal');
  }

  /* A triangle with chosen labels on sides and angles. */
  function triangle(opts) {
    opts = opts || {};
    var W = 260, H = 170;
    var A = opts.A || [30, 140], B = opts.B || [225, 140], C = opts.C || [95, 35];
    var body = poly([A, B, C], { fill: 'none' });
    if (opts.right) body += rightAngle(A, B, C, 11);
    (opts.angles || []).forEach(function (a) {
      var v = { A: A, B: B, C: C }[a.at];
      var o1 = { A: B, B: C, C: A }[a.at], o2 = { A: C, B: A, C: B }[a.at];
      var u1 = unit(v, o1), u2 = unit(v, o2);
      var bis = [(u1[0] + u2[0]) / 2, (u1[1] + u2[1]) / 2];
      var L = Math.hypot(bis[0], bis[1]) || 1;
      body += text(v[0] + bis[0] / L * 30, v[1] + bis[1] / L * 30 + 4, a.label, { colour: ACC, size: 12 });
    });
    (opts.sides || []).forEach(function (s) {
      var p = { AB: A, BC: B, CA: C }[s.on], q = { AB: B, BC: C, CA: A }[s.on];
      var mx = (p[0] + q[0]) / 2, my = (p[1] + q[1]) / 2;
      var u = unit(p, q), n = [-u[1], u[0]];
      body += text(mx + n[0] * 14, my + n[1] * 14 + 4, s.label, { size: 12 });
      if (s.ticks) body += ticks(p, q, s.ticks);
    });
    if (opts.names !== false) {
      body += text(A[0] - 10, A[1] + 12, 'A', { colour: MUT, size: 12 });
      body += text(B[0] + 11, B[1] + 12, 'B', { colour: MUT, size: 12 });
      body += text(C[0] - 2, C[1] - 7, 'C', { colour: MUT, size: 12 });
    }
    return svg(W, H, body, 'a triangle');
  }

  /* A triangle drawn from two of its angles, so the picture is true to its numbers. */
  function triangleAngles(alpha, beta, opts) {
    opts = opts || {};
    var a = alpha * Math.PI / 180, b = beta * Math.PI / 180;
    var ac = Math.sin(b) / Math.sin(a + b);                      /* with AB = 1 */
    var cx = ac * Math.cos(a), cy = ac * Math.sin(a);
    var minX = Math.min(0, cx), maxX = Math.max(1, cx);
    var sc = Math.min(205 / (maxX - minX), 112 / cy);
    var x0 = 28 + (205 - (maxX - minX) * sc) / 2 - minX * sc, yb = 146;
    var o = {};
    for (var k in opts) o[k] = opts[k];
    o.A = [x0, yb]; o.B = [x0 + sc, yb]; o.C = [x0 + cx * sc, yb - cy * sc];
    return triangle(o);
  }

  /* A right triangle, right angle bottom-left, drawn to the real leg lengths. */
  function rightTriangle(adj, opp, opts) {
    opts = opts || {};
    var sc = Math.min(190 / adj, 108 / opp);
    var A = [38, 146], B = [38 + adj * sc, 146], C = [38, 146 - opp * sc];
    var body = poly([A, B, C]) + rightAngle(A, B, C, 11);
    var M = [(B[0] + C[0]) / 2, (B[1] + C[1]) / 2], n = unit(A, M);
    if (opts.bottom !== undefined) body += text((A[0] + B[0]) / 2, A[1] + 17, opts.bottom);
    if (opts.left !== undefined) body += text(A[0] - 9, (A[1] + C[1]) / 2 + 4, opts.left, { anchor: 'end' });
    if (opts.hyp !== undefined) body += text(M[0] + n[0] * 15, M[1] + n[1] * 15 + 4, opts.hyp);
    if (opts.theta) body += text(B[0] - 34, B[1] - 8, opts.theta, { colour: ACC });
    return svg(260, 170, body, 'a right triangle');
  }

  /* Angle of elevation (looking up from the ground) or depression (looking down from
     a height), drawn at the real angle so the picture agrees with its label. */
  function elevation(kind, deg, labels) {
    var L = labels || {}, a = deg * Math.PI / 180;
    var X = Math.min(190, 105 / Math.tan(a)), Y = X * Math.tan(a), gy = 142, body = '';
    body += line(18, gy, 242, gy, { colour: MUT });
    if (kind === 'depression') {
      var ox = 38, oy = gy - Y;                                   /* observer on top of a cliff */
      body += line(ox, oy, ox, gy) + line(ox, oy, ox + X, gy, { colour: ACC, w: 2 }) +
        line(ox, oy, ox + Math.min(X + 24, 215), oy, { dash: true, colour: MUT });
      body += arc(ox, oy, 34, -deg, 0) + dot(ox, oy) + dot(ox + X, gy);
      body += text(ox + 50 * Math.cos(a / 2), oy + 50 * Math.sin(a / 2) + 4, L.angle || deg + '\u00b0', { colour: ACC, anchor: 'start' });
      body += text(ox - 7, (oy + gy) / 2 + 4, L.height || 'h', { anchor: 'end' });
      body += text(ox + X / 2, gy + 15, L.dist || 'd');
    } else {
      var ex = 38;                                                /* observer on the ground */
      body += line(ex + X, gy, ex + X, gy - Y) + line(ex, gy, ex + X, gy - Y, { colour: ACC, w: 2 });
      body += arc(ex, gy, 34, 0, deg) + dot(ex, gy) + dot(ex + X, gy - Y);
      body += text(ex + 50 * Math.cos(a / 2), gy - 50 * Math.sin(a / 2) + 4, L.angle || deg + '\u00b0', { colour: ACC, anchor: 'start' });
      body += text(ex + X + 8, gy - Y / 2 + 4, L.height || 'h', { anchor: 'start' });
      body += text(ex + X / 2, gy + 15, L.dist || 'd');
    }
    return svg(260, 170, body, 'an angle of ' + kind);
  }

  /* A circle with the named parts drawn on it. Angles are drawn at their real size. */
  function circleFig(parts, labels) {
    var W = 290, H = 210, c = [125, 105], rad = 75;
    var body = circle(c[0], c[1], rad) + dot(c[0], c[1]) +
      text(c[0] - 9, c[1] - 7, 'O', { colour: MUT, size: 12 });
    parts = parts || [];
    labels = labels || {};
    function on(deg) { var a = deg * Math.PI / 180; return [c[0] + rad * Math.cos(a), c[1] - rad * Math.sin(a)]; }
    if (parts.indexOf('radius') > -1) {
      var p = on(35), u = unit(c, p), nrm = [u[1], -u[0]];
      var mid = [(c[0] + p[0]) / 2, (c[1] + p[1]) / 2];
      body += line(c[0], c[1], p[0], p[1], { colour: ACC, w: 2 });
      body += text(mid[0] + nrm[0] * 11, mid[1] + nrm[1] * 11 + 3, labels.radius || 'r', { colour: ACC, anchor: 'end' });
    }
    if (parts.indexOf('diameter') > -1) {
      body += line(on(200)[0], on(200)[1], on(20)[0], on(20)[1], { colour: ACC, w: 2 });
      body += text(c[0], c[1] + 20, labels.diameter || 'd', { colour: ACC });
    }
    if (parts.indexOf('chord') > -1) {
      body += line(on(230)[0], on(230)[1], on(310)[0], on(310)[1], { colour: ACC, w: 2 });
      body += text(c[0], c[1] + rad - 4, labels.chord || 'chord', { colour: ACC, size: 11 });
    }
    if (parts.indexOf('tangent') > -1) {
      var t = on(0);
      body += line(t[0], t[1] - 60, t[0], t[1] + 60, { colour: ACC, w: 2 });
      body += dot(t[0], t[1]);
      body += text(t[0] + 9, t[1] - 38, labels.tangent || 'tangent', { colour: ACC, size: 11, anchor: 'start' });
    }
    if (parts.indexOf('sector') > -1) {
      var deg = labels.sectorAngle === undefined ? 70 : labels.sectorAngle;
      var s1 = on(90), s2 = on(90 - deg);
      body += '<path d="M ' + r(c[0]) + ' ' + r(c[1]) + ' L ' + r(s1[0]) + ' ' + r(s1[1]) +
        ' A ' + rad + ' ' + rad + ' 0 ' + (deg > 180 ? 1 : 0) + ' 1 ' + r(s2[0]) + ' ' + r(s2[1]) +
        ' Z" fill="var(--accent-soft)" stroke="' + ACC + '" stroke-width="1.6"/>';
      var mid2 = (90 - deg / 2) * Math.PI / 180;
      body += text(c[0] + 40 * Math.cos(mid2), c[1] - 40 * Math.sin(mid2) + 4, deg + '\u00b0', { colour: ACC, size: 12 });
    }
    if (parts.indexOf('central') > -1 || parts.indexOf('inscribed') > -1) {
      var deg2 = labels.angle === undefined ? 80 : labels.angle;
      var A = on(90 + deg2 / 2), B = on(90 - deg2 / 2);
      body += line(A[0], A[1], c[0], c[1], { colour: MUT }) + line(B[0], B[1], c[0], c[1], { colour: MUT });
      body += dot(A[0], A[1]) + dot(B[0], B[1]);
      if (parts.indexOf('inscribed') > -1) {
        var P = on(270);
        body += line(A[0], A[1], P[0], P[1], { colour: ACC, w: 2 }) +
                line(B[0], B[1], P[0], P[1], { colour: ACC, w: 2 }) + dot(P[0], P[1]);
        body += text(P[0], P[1] - 24, '?', { colour: ACC, size: 12 });
        body += text(P[0], P[1] + 16, 'P', { colour: ACC, size: 12 });
      }
      body += text(c[0], c[1] - 34, deg2 + '\u00b0', { colour: MUT, size: 12 });
    }
    return svg(W, H, body, 'a circle diagram');
  }

  /* A coordinate grid with points, segments and an optional shape. */
  function grid(opts) {
    opts = opts || {};
    var span = opts.span || 6;                 /* axes run -span .. span */
    var W = 250, H = 250, pad = 22;
    var unitPx = (W - 2 * pad) / (2 * span);
    function X(x) { return pad + (x + span) * unitPx; }
    function Y(y) { return H - pad - (y + span) * unitPx; }
    var body = '';
    for (var i = -span; i <= span; i++) {
      body += line(X(i), Y(-span), X(i), Y(span), { colour: 'var(--rule)', w: 1 });
      body += line(X(-span), Y(i), X(span), Y(i), { colour: 'var(--rule)', w: 1 });
    }
    body += line(X(-span), Y(0), X(span), Y(0), { colour: MUT, w: 1.4 });
    body += line(X(0), Y(-span), X(0), Y(span), { colour: MUT, w: 1.4 });
    body += text(X(span) - 6, Y(0) + 14, 'x', { colour: MUT, size: 11 });
    body += text(X(0) - 10, Y(span) + 10, 'y', { colour: MUT, size: 11 });
    (opts.shapes || []).forEach(function (sh) {
      body += poly(sh.points.map(function (p) { return [X(p[0]), Y(p[1])]; }),
        { colour: sh.colour || INK, fill: sh.fill || 'none', w: sh.w || 1.8 });
    });
    (opts.segments || []).forEach(function (s) {
      body += line(X(s[0][0]), Y(s[0][1]), X(s[1][0]), Y(s[1][1]), { colour: s[2] || ACC, w: 2, dash: s[3] });
    });
    (opts.points || []).forEach(function (p) {
      body += dot(X(p[0]), Y(p[1]), { colour: p.colour || ACC, rad: 3.5 });
      if (p[2]) body += text(X(p[0]) + 9, Y(p[1]) - 7, p[2], { colour: p.colour || ACC, size: 11, anchor: 'start' });
    });
    return svg(W, H, body, 'a coordinate grid');
  }

  /* Schematic figures say so, rather than implying a scale they do not have. */
  function notToScale(H) { return text(8, H - 5, 'not to scale', { size: 9, colour: MUT, anchor: 'start', halo: false }); }

  /* A labelled rectangle, triangle, trapezium, parallelogram or composite. */
  function areaShape(kind, labels) {
    var W = 250, H = 160;
    var body = '', L = labels || {};
    if (kind === 'rectangle') {
      body += poly([[35, 30], [215, 30], [215, 125], [35, 125]]);
      body += text(125, 22, L.base || 'b') + text(226, 80, L.height || 'h', { anchor: 'start' });
      body += rightAngle([35, 125], [215, 125], [35, 30], 10) + notToScale(H);
    } else if (kind === 'triangle') {
      body += poly([[35, 125], [215, 125], [120, 32]]);
      body += line(120, 32, 120, 125, { dash: true, colour: MUT });
      body += rightAngle([120, 125], [215, 125], [120, 32], 9);
      body += text(125, 140, L.base || 'b') + text(130, 85, L.height || 'h', { anchor: 'start', colour: MUT }) + notToScale(H);
    } else if (kind === 'parallelogram') {
      body += poly([[55, 125], [215, 125], [185, 35], [25, 35]]);
      body += line(55, 125, 55, 35, { dash: true, colour: MUT });
      body += rightAngle([55, 125], [215, 125], [55, 35], 9);
      body += text(135, 140, L.base || 'b') + text(63, 85, L.height || 'h', { anchor: 'start', colour: MUT }) + notToScale(H);
    } else if (kind === 'trapezium') {
      body += poly([[30, 125], [220, 125], [180, 35], [75, 35]]);
      body += line(75, 125, 75, 35, { dash: true, colour: MUT });
      body += text(127, 28, L.top || 'a') + text(125, 140, L.base || 'b') +
              text(83, 85, L.height || 'h', { anchor: 'start', colour: MUT }) + notToScale(H);
    } else if (kind === 'composite') {
      /* the L-shape is drawn to scale: a rectangle with a corner cut away */
      var Wd = +L.W || 15, Hd = +L.H || 11, wd = +L.w || 4, hd = +L.h || 7;
      var sc = Math.min(180 / Wd, 88 / Hd), x0 = 35, yb = 125;
      var xs = x0 + (Wd - wd) * sc, xr = x0 + Wd * sc, yt = yb - Hd * sc, yn = yb - (Hd - hd) * sc;
      body += poly([[x0, yb], [x0, yt], [xs, yt], [xs, yn], [xr, yn], [xr, yb]]);
      body += text((x0 + xs) / 2, yt - 7, L.top || '') + text((xs + xr) / 2, yn - 7, L.notchW || '');
      body += text(xs + 7, (yt + yn) / 2 + 4, L.notchH || '', { anchor: 'start' });
      body += text((x0 + xr) / 2, yb + 17, L.base || '') + text(x0 - 8, (yt + yb) / 2 + 4, L.height || '', { anchor: 'end' });
    }
    return svg(W, H, body, 'a ' + kind);
  }

  /* A rough sketch of a solid, labelled. */
  function solid(kind, labels) {
    var W = 240, H = 180, L = labels || {}, body = '';
    if (kind === 'prism' || kind === 'cuboid') {
      body += poly([[40, 60], [150, 60], [150, 140], [40, 140]]);
      body += poly([[40, 60], [75, 30], [185, 30], [150, 60]], { colour: MUT });
      body += poly([[150, 60], [185, 30], [185, 110], [150, 140]], { colour: MUT });
      body += text(95, 156, L.length || 'l') + text(198, 90, L.width || 'w', { anchor: 'start', colour: MUT }) +
              text(32, 104, L.height || 'h', { anchor: 'end' });
    } else if (kind === 'cylinder') {
      body += '<ellipse cx="120" cy="45" rx="55" ry="18" fill="none" stroke="' + INK + '" stroke-width="1.6"/>';
      body += line(65, 45, 65, 135) + line(175, 45, 175, 135);
      body += '<path d="M 65 135 A 55 18 0 0 0 175 135" fill="none" stroke="' + INK + '" stroke-width="1.6"/>';
      body += '<path d="M 65 135 A 55 18 0 0 1 175 135" fill="none" stroke="' + MUT + '" stroke-width="1.2" stroke-dasharray="4 4"/>';
      body += line(120, 45, 175, 45, { colour: ACC, w: 2 }) + text(182, 49, L.radius || 'r', { colour: ACC, anchor: 'start' });
      body += text(187, 98, L.height || 'h', { anchor: 'start' });
    } else if (kind === 'cone') {
      body += '<ellipse cx="120" cy="135" rx="55" ry="17" fill="none" stroke="' + INK + '" stroke-width="1.6"/>';
      body += line(65, 135, 120, 35) + line(175, 135, 120, 35);
      body += line(120, 135, 120, 35, { dash: true, colour: MUT });
      body += line(120, 135, 175, 135, { colour: ACC, w: 2 }) + text(182, 139, L.radius || 'r', { colour: ACC, anchor: 'start' });
      body += text(120, 92, L.height || 'h', { colour: MUT });
    } else if (kind === 'pyramid') {
      body += poly([[50, 135], [150, 135], [185, 110], [85, 110]], { colour: MUT });
      body += line(50, 135, 118, 35) + line(150, 135, 118, 35) + line(185, 110, 118, 35);
      body += line(118, 110, 118, 35, { dash: true, colour: MUT });
      body += text(100, 152, L.base || 's') + text(118, 82, L.height || 'h', { colour: MUT });
    } else if (kind === 'sphere') {
      body += circle(120, 90, 60);
      body += '<ellipse cx="120" cy="90" rx="60" ry="18" fill="none" stroke="' + MUT +
              '" stroke-width="1.2" stroke-dasharray="4 4"/>';
      body += line(120, 90, 180, 90, { colour: ACC, w: 2 }) + dot(120, 90);
      body += text(187, 94, L.radius || 'r', { colour: ACC, anchor: 'start' });
    }
    return svg(W, H, body + notToScale(H), 'a ' + kind);
  }

  /* A shape and its image under a transformation, with matching vertices labelled
     A, B, C and A', B', C' so a learner can follow one point from start to finish. */
  function transform(kind, pts, image) {
    var names = ['A', 'B', 'C', 'D'], span = 6;
    pts.concat(image).forEach(function (p) { span = Math.max(span, Math.abs(p[0]) + 1, Math.abs(p[1]) + 1); });
    var pa = pts.map(function (p, i) { var q = [p[0], p[1], names[i]]; q.colour = INK; return q; });
    var pb = image.map(function (p, i) { var q = [p[0], p[1], names[i] + '\u2032']; q.colour = ACC; return q; });
    return grid({ span: span, shapes: [{ points: pts, colour: INK }, { points: image, colour: ACC, w: 2 }],
      points: pa.concat(pb) });
  }

  var F = {
    svg: svg, line: line, poly: poly, circle: circle, dot: dot, text: text, arc: arc,
    rightAngle: rightAngle, ticks: ticks,
    angleAt: angleAt, anglePair: anglePair, transversal: transversal, triangle: triangle,
    triangleAngles: triangleAngles, rightTriangle: rightTriangle, elevation: elevation,
    circleFig: circleFig, grid: grid, areaShape: areaShape, solid: solid, transform: transform
  };
  root.FIGURES = F;
  if (typeof module !== 'undefined' && module.exports) module.exports = F;
})(typeof window !== 'undefined' ? window : globalThis);
